previews:
  generation: automatic

services:
  - type: worker
    name: liquidator
    plan: starter
    runtime: node
    region: frankfurt
    buildCommand: pnpm install && pnpm db:generate && pnpm build
    startCommand: pnpm tsx src/index.ts
    autoDeploy: true
    envVars:
      - fromGroup: liquidator
