-- AlterTable
ALTER TABLE "Liquidation" ALTER COLUMN "seizedAssets" SET DATA TYPE DECIMAL(78,0),
ALTER COLUMN "repaidShares" SET DATA TYPE DECIMAL(78,0);

-- AlterTable
ALTER TABLE "Market" ALTER COLUMN "lltv" SET DATA TYPE DECIMAL(78,0);

-- AlterTable
ALTER TABLE "Position" ALTER COLUMN "borrowShares" SET DATA TYPE DECIMAL(78,0),
ALTER COLUMN "collateral" SET DATA TYPE DECIMAL(78,0),
ALTER COLUMN "supplyShares" SET DATA TYPE DECIMAL(78,0);
